name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 72.62.71.161
          username: root
          key: ${{ secrets.MESBAH_SERVER_SSH_KEY }}
          script: |
            cd /www/wwwroot/mesbah.ae
            git pull origin main
